<?php

namespace Hff\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AutoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoresRepository extends EntityRepository
{
}
