<?php

namespace Hff\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository
{
    public function findAllOrderByUsuario()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT u FROM HffBlogBundle:Usuarios u ORDER BY u.usuario')
            ->getResult();
    }
}
