hff_blog:
    resource: "@HffBlogBundle/Resources/config/routing.yml"
    prefix:   /
    
sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /cubil
    
_sonata_admin:
    resource: .
    type:   sonata_admin
    prefix: /cubil
    
sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /
    
#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery
#
#media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media


