jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
      Hff\BlogBundle\Entity\Usuarios: { algorithm: sha512, iterations: 10} 

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ESCRITOR
        ROLE_SUPER_ADMIN: [ROLE_ESCRITOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
       usuarios:
          entity: { class: Hff\BlogBundle\Entity\Usuarios, property: usuario }
        #in_memory:
         #   memory:
          #      users:
           #         user:  { password: userpass, roles: [ 'ROLE_USER' ] }
            #        admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        permitir_login:
            pattern:  ^/login$
            #anonymous:  ~
            security: false

        permitir_usuario_nuevo:
            pattern:  ^/usuarios/registrar
            security: false
            #anonymous:  ~
        
        usuario_nuevo:
            pattern:  ^/usuarios/new
            anonymous:  ~

        area_restringida:
            pattern:    ^/*
            form_login:
                login_path: usuarios_login
                check_path: usuarios_login_check
            logout:
                path:       usuarios_logout
            remember_me:
                key:        HFF2011201X
                lifetime:   604800  #Recordar durante una semana


   # access_control:
   # - { path: ^/usuarios/(edit|delete), roles: ROLE_ADMIN }
   # - { path: ^/usuarios/show, roles: ROLE_ESCRITOR }
      
        # { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
