<?php

namespace Hff\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CitasController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Hff\BlogBundle\Controller\CitasController();
        return $instance;
    }
}
