parameters:
    # direcci贸n de correo electr贸nico para contacto del Homefanfics
    hff_blog.emails.contacto: carlosmatamala@gmail.com
    # direcci贸n de correo electr贸nico no-reply
    hff_blog.emails.no_reply: no-reply@homefanfics.com
