hff_blog_homepage:
    pattern:  /
    defaults: { _controller: HffBlogBundle:Paginas:index }
    requirements:
        _method:  GET
        
autores_create:
    pattern:  /autores/create
    defaults: { _controller: HffBlogBundle:Autores:create } 
    
autores_new:
    pattern:  /autores/new
    defaults: { _controller: HffBlogBundle:Autores:new }

autores:
    pattern:  /autores
    defaults: { _controller: HffBlogBundle:Autores:index }    
    
autores_show:
    pattern:  /autores/show/{id}
    defaults: { _controller: HffBlogBundle:Autores:show }
    
autores_edit:
    pattern:  /autores/edit/{id}
    defaults: { _controller: HffBlogBundle:Autores:edit }  
    
autores_delete:
    pattern:  /autores/delete/{id}
    defaults: { _controller: HffBlogBundle:Autores:delete } 
    
autores_update:
    pattern:  /autores/update/{id}
    defaults: { _controller: HffBlogBundle:Autores:update } 
    
citas_create:
    pattern:  /citas/create
    defaults: { _controller: HffBlogBundle:Citas:create } 
    
citas_new:
    pattern:  /citas/new
    defaults: { _controller: HffBlogBundle:Citas:new }

citas:
    pattern:  /citas
    defaults: { _controller: HffBlogBundle:Citas:index }    
    
citas_show:
    pattern:  /citas/show/{id}
    defaults: { _controller: HffBlogBundle:Citas:show }
    
citas_edit:
    pattern:  /citas/edit/{id}
    defaults: { _controller: HffBlogBundle:Citas:edit }  
    
citas_delete:
    pattern:  /citas/delete/{id}
    defaults: { _controller: HffBlogBundle:Citas:delete } 
    
citas_update:
    pattern:  /citas/update/{id}
    defaults: { _controller: HffBlogBundle:Citas:update } 
    
citas_listar:
    pattern:  /citas/listar
    defaults: { _controller: HffBlogBundle:Citas:listar }
    
categorias_create:
    pattern:  /categorias/create
    defaults: { _controller: HffBlogBundle:Categorias:create } 
    
categorias_new:
    pattern:  /categorias/new
    defaults: { _controller: HffBlogBundle:Categorias:new }

categorias:
    pattern:  /categorias
    defaults: { _controller: HffBlogBundle:Categorias:index }
    
categorias_show:
    pattern:  /categorias/show/{id}
    defaults: { _controller: HffBlogBundle:Categorias:show }
    
categorias_edit:
    pattern:  /categorias/edit/{id}
    defaults: { _controller: HffBlogBundle:Categorias:edit }  
    
categorias_delete:
    pattern:  /categorias/delete/{id}
    defaults: { _controller: HffBlogBundle:Categorias:delete } 
    
categorias_update:
    pattern:  /categorias/update/{id}
    defaults: { _controller: HffBlogBundle:Categorias:update }     
    
usuario_registrar:
    pattern:  /usuario/registrar
    defaults: { _controller: HffBlogBundle:Usuarios:registrar } 

usuarios_create:
    pattern:  /usuarios/create
    defaults: { _controller: HffBlogBundle:Usuarios:create } 
    
usuarios_new:
    pattern:  /usuarios/new
    defaults: { _controller: HffBlogBundle:Usuarios:new }

usuarios:
    pattern:  /usuarios
    defaults: { _controller: HffBlogBundle:Usuarios:index }
    
usuarios_show:
    pattern:  /usuarios/show/{id}
    defaults: { _controller: HffBlogBundle:Usuarios:show }
    
usuarios_edit:
    pattern:  /usuarios/edit/{id}
    defaults: { _controller: HffBlogBundle:Usuarios:edit }  
    
usuarios_delete:
    pattern:  /usuarios/delete/{id}
    defaults: { _controller: HffBlogBundle:Usuarios:delete } 
    
usuarios_update:
    pattern:  /usuarios/update/{id}
    defaults: { _controller: HffBlogBundle:Usuarios:update }
    
usuarios_login:
    pattern:   /login
    defaults:  { _controller: HffBlogBundle:Usuarios:login }


usuarios_login_check:
    pattern:   /usuarios/login_check

usuarios_logout:
    pattern:   /logout
    
HffBlogBundle_contacto:
    pattern:  /contacto
    defaults: { _controller: HffBlogBundle:Paginas:contacto }
    requirements:
        _method:  GET|POST