inicio:
    pattern:  /
    defaults: { _controller: HffBlogBundle:Paginas:index }
    requirements:
        _method:  GET
        
autores_create:
    pattern:  /autores/create
    defaults: { _controller: HffBlogBundle:Autores:create } 
    
autores_new:
    pattern:  /autores/new
    defaults: { _controller: HffBlogBundle:Autores:new }

autores:
    pattern:  /autores
    defaults: { _controller: HffBlogBundle:Autores:index }    
    
autores_show:
    pattern:  /autores/show/{id}
    defaults: { _controller: HffBlogBundle:Autores:show }
    
autores_edit:
    pattern:  /autores/edit/{id}
    defaults: { _controller: HffBlogBundle:Autores:edit }  
    
autores_delete:
    pattern:  /autores/delete/{id}
    defaults: { _controller: HffBlogBundle:Autores:delete } 
    
autores_update:
    pattern:  /autores/update/{id}
    defaults: { _controller: HffBlogBundle:Autores:update } 
    
citas_create:
    pattern:  /citas/create
    defaults: { _controller: HffBlogBundle:Citas:create } 
    
citas_new:
    pattern:  /citas/new
    defaults: { _controller: HffBlogBundle:Citas:new }

citas:
    pattern:  /citas
    defaults: { _controller: HffBlogBundle:Citas:index }    
    
citas_show:
    pattern:  /citas/show/{id}
    defaults: { _controller: HffBlogBundle:Citas:show }
    
citas_edit:
    pattern:  /citas/edit/{id}
    defaults: { _controller: HffBlogBundle:Citas:edit }  
    
citas_delete:
    pattern:  /citas/delete/{id}
    defaults: { _controller: HffBlogBundle:Citas:delete } 
    
citas_update:
    pattern:  /citas/update/{id}
    defaults: { _controller: HffBlogBundle:Citas:update } 
    
citas_listar:
    pattern:  /citas/listar
    defaults: { _controller: HffBlogBundle:Citas:listar }

# CATEGORIA ***************************************************

categoria:
    pattern:  /categoria
    defaults: { _controller: HffBlogBundle:Categorias:index }
    
categoria_crear:
    pattern:  /categoria/crear
    defaults: { _controller: HffBlogBundle:Categorias:crear } 
    
categoria_nueva:
    pattern:  /categoria/nueva
    defaults: { _controller: HffBlogBundle:Categorias:nueva }
    
categoria_ver:
    pattern:  /categoria/ver/{id}
    defaults: { _controller: HffBlogBundle:Categorias:ver }
    
categoria_editar:
    pattern:  /categoria/editar/{id}
    defaults: { _controller: HffBlogBundle:Categorias:editar }  
    
categoria_borrar:
    pattern:  /categoria/borrar/{id}
    defaults: { _controller: HffBlogBundle:Categorias:borrar } 
    
categoria_actualizar:
    pattern:  /categoria/actualizar/{id}
    defaults: { _controller: HffBlogBundle:Categorias:actualizar }

# COMENTARIOS ***************************************************      
    
comentario:
    pattern:  /comentario
    defaults: { _controller: HffBlogBundle:Comentarios:index }  

comentario_crear:
    pattern:  /comentario/crear
    defaults: { _controller: HffBlogBundle:Comentarios:crear } 
    
comentario_nuevo:
    pattern:  /comentario/nuevo
    defaults: { _controller: HffBlogBundle:Comentarios:nuevo }
    
comentario_ver:
    pattern:  /comentario/ver/{id}
    defaults: { _controller: HffBlogBundle:Comentarios:ver }
    
comentario_editar:
    pattern:  /comentario/editar/{id}
    defaults: { _controller: HffBlogBundle:Comentarios:editar }  
    
comentario_borrar:
    pattern:  /comentario/borrar/{id}
    defaults: { _controller: HffBlogBundle:Comentarios:borrar } 
    
comentario_actualizar:
    pattern:  /comentario/actualizar/{id}
    defaults: { _controller: HffBlogBundle:Comentarios:actualizar }
    
# ESCRITOS ***************************************************      
    
escrito:
    pattern:  /escrito
    defaults: { _controller: HffBlogBundle:Escritos:index }  

escrito_crear:
    pattern:  /escrito/crear
    defaults: { _controller: HffBlogBundle:Escritos:crear } 
    
escrito_nuevo:
    pattern:  /escrito/nuevo
    defaults: { _controller: HffBlogBundle:Escritos:nuevo }
    
escrito_ver:
    pattern:  /escrito/ver/{id}
    defaults: { _controller: HffBlogBundle:Escritos:ver }
    
escrito_editar:
    pattern:  /escrito/editar/{id}
    defaults: { _controller: HffBlogBundle:Escritos:editar }  
    
escrito_borrar:
    pattern:  /escrito/borrar/{id}
    defaults: { _controller: HffBlogBundle:Escritos:borrar } 
    
escrito_actualizar:
    pattern:  /escrito/actualizar/{id}
    defaults: { _controller: HffBlogBundle:Escritos:actualizar }
    
# USUARIOS ***************************************************   
    
usuario:
    pattern:  /usuario
    defaults: { _controller: HffBlogBundle:Usuarios:index }
    
usuario_registrar:
    pattern:  /registrar
    defaults: { _controller: HffBlogBundle:Usuarios:registrar }

usuario_crear:
    pattern:  /usuario/crear
    defaults: { _controller: HffBlogBundle:Usuarios:crear } 
    
usuario_nuevo:
    pattern:  /usuario/nuevo
    defaults: { _controller: HffBlogBundle:Usuarios:nuevo }

   
usuario_ver:
    pattern:  /usuario/ver/{id}
    defaults: { _controller: HffBlogBundle:Usuarios:ver }
    
usuario_editar:
    pattern:  /usuario/editar/{id}
    defaults: { _controller: HffBlogBundle:Usuarios:editar }  
    
usuario_borrar:
    pattern:  /usuario/borrar/{id}
    defaults: { _controller: HffBlogBundle:Usuarios:borrar } 
    
usuario_actualizar:
    pattern:  /usuario/actualizar/{id}
    defaults: { _controller: HffBlogBundle:Usuarios:actualizar }
    
usuarios_login:
    pattern:   /login
    defaults:  { _controller: HffBlogBundle:Usuarios:login }


usuarios_login_check:
    pattern:   /usuarios/login_check

usuarios_logout:
    pattern:   /logout
    
HffBlogBundle_contacto:
    pattern:  /contacto
    defaults: { _controller: HffBlogBundle:Paginas:contacto }
    requirements:
        _method:  GET|POST
        