hff_blog_homepage:
    pattern:  /
    defaults: { _controller: HffBlogBundle:Paginas:index }
    requirements:
        _method:  GET
        
autores_new:
    pattern:  /autores/new
    defaults: { _controller: HffBlogBundle:Autores:new }
    
autores:
    pattern:  /autores
    defaults: { _controller: HffBlogBundle:Autores:index }
    
autores_show:
    pattern:  /autores/show/{id}
    defaults: { _controller: HffBlogBundle:Autores:show }
    
autores_edit:
    pattern:  /autores/edit/{id}
    defaults: { _controller: HffBlogBundle:Autores:edit }  
    
autores_delete:
    pattern:  /autores/delete/{id}
    defaults: { _controller: HffBlogBundle:Autores:delete } 
    
autores_update:
    pattern:  /autores/update/{id}
    defaults: { _controller: HffBlogBundle:Autores:update } 
    
citas_listar:
    pattern:  /citas/listar
    defaults: { _controller: HffBlogBundle:Citas:listar }
    
usuario_crear:
    pattern:  /usuario/crear
    defaults: { _controller: HffBlogBundle:Usuarios:crear }   