parameters:
#    hff_blog.example.class: Hff\BlogBundle\Example

services:
#    hff_blog.example:
#        class: %hff_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
